# Generated by Django 4.2.21 on 2025-06-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestrabiologica',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='muestras/imagenes/', verbose_name='Imagen de la muestra'),
        ),
    ]
