# Generated by Django 4.2.21 on 2025-06-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_muestrabiologica_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestrabiologica',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='muestras/', verbose_name='Imagen de la muestra'),
        ),
    ]
