# Generated by Django 4.2.21 on 2025-06-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_muestrabiologica_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestrabiologica',
            name='imagen',
            field=models.ImageField(null=True, upload_to='muestras/imagenes/', verbose_name='Imagen de la muestra'),
        ),
        migrations.AlterField(
            model_name='muestrabiologica',
            name='numero_recolecta',
            field=models.CharField(unique=True),
        ),
    ]
