# Generated by Django 4.2.21 on 2025-06-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_muestrabiologica_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestrabiologica',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.familia', verbose_name='Familia'),
        ),
    ]
