# Generated by Django 4.2.21 on 2025-06-23 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_muestrabiologica_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestrabiologica',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=47, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='muestrabiologica',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=47, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
